server:
  port: 8080

spring:
  application:
    name: school-app


# custom path for swagger-ui
springdoc:
  swagger-ui:
    path: /api.html
    operationsSorter: method
  api-docs:
    path: /api-docs

